apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: security

configMapGenerator:
  - name: keycloak-bootstrap
    files:
      - bootstrap.sh=../../platform/keycloak/bootstrap.sh
    options:
      disableNameSuffixHash: true
  - name: keycloak-realm
    files:
      - realm-fluxo-caixa.json=../../platform/keycloak/realm-fluxo-caixa.json
    options:
      disableNameSuffixHash: true

resources:
  - connection-configmap.yaml
  - bootstrap-job.yaml
