apiVersion: v1
kind: Service
metadata:
  name: svc-lancamentos
  labels:
    app.kubernetes.io/name: svc-lancamentos
    app.kubernetes.io/part-of: fluxo-caixa
spec:
  selector:
    app: svc-lancamentos
  ports:
    - name: http
      port: 8000
      targetPort: http
