apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gateway

configMapGenerator:
  - name: krakend-config
    files:
      - krakend.json=../../platform/krakend/krakend.json
    options:
      disableNameSuffixHash: true

resources:
  - connection-configmap.yaml
  - deployment.yaml
  - service.yaml
