apiVersion: v1
kind: Service
metadata:
  name: krakend
  labels:
    app.kubernetes.io/name: krakend
    app.kubernetes.io/part-of: fluxo-caixa
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: krakend
  ports:
    - name: https
      port: 8080
      targetPort: 8080
      nodePort: 30443
      protocol: TCP
