#!/usr/bin/env bash
# Harbor / k3s / Podman registry resolution — self-contained in-VM vs legacy external.
# Source after scripts/lib/common.sh. Requires write_if_changed + run_as_root in caller
# (bootstrap-vm.sh, deploy-registry.sh) or define stubs below.

set -euo pipefail

REGISTRY_ENV_FILE="${REGISTRY_ENV_FILE:-/etc/fluxo-caixa/registry.env}"
K3S_REGISTRIES="${K3S_REGISTRIES:-/etc/rancher/k3s/registries.yaml}"
PODMAN_REGISTRIES="${PODMAN_REGISTRIES:-/etc/containers/registries.conf.d/999-harbor.conf}"
HARBOR_PROJECT="${HARBOR_PROJECT:-fluxo-caixa}"
HARBOR_ALIAS="${HARBOR_ALIAS:-harbor.local}"
HARBOR_PORT="${HARBOR_PORT:-8080}"
HARBOR_INSTALL_DIR="${HARBOR_INSTALL_DIR:-/opt/harbor}"
HARBOR_ADMIN_USER="${HARBOR_ADMIN_USER:-admin}"
HARBOR_ADMIN_PASSWORD="${HARBOR_ADMIN_PASSWORD:-Harbor12345}"

SCRIPT_DIR_REGISTRY="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT_REGISTRY="$(cd "${SCRIPT_DIR_REGISTRY}/../.." && pwd)"
HARBOR_CA_CERT="${HARBOR_CA_CERT:-${REPO_ROOT_REGISTRY}/deploy/certs/harbor-ca.crt}"
REGISTRIES_TEMPLATE="${REGISTRIES_TEMPLATE:-${REPO_ROOT_REGISTRY}/deploy/registry/registries.yaml.in}"
PODMAN_REGISTRIES_TEMPLATE="${PODMAN_REGISTRIES_TEMPLATE:-${REPO_ROOT_REGISTRY}/deploy/registry/podman-registries.conf.in}"

# Populated by resolve_harbor_config()
HARBOR_MODE=""
HARBOR_HOST=""
HARBOR_REGISTRY=""
HARBOR_IMAGE_REGISTRY=""
HARBOR_API_BASE=""

detect_vm_primary_ip() {
  local ip
  ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  echo "${ip:-127.0.0.1}"
}

parse_harbor_external() {
  local external="${1}"
  local host port
  if [[ "${external}" == *:* ]]; then
    host="${external%%:*}"
    port="${external##*:}"
  else
    host="${external}"
    port="${HARBOR_PORT}"
  fi
  HARBOR_HOST="${host}"
  HARBOR_PORT="${port}"
}

resolve_harbor_config() {
  if [[ "${SELF_CONTAINED:-1}" == "0" ]] || [[ -n "${HARBOR_EXTERNAL:-}" ]]; then
    HARBOR_MODE="external"
    if [[ -n "${HARBOR_EXTERNAL:-}" ]]; then
      parse_harbor_external "${HARBOR_EXTERNAL}"
    elif [[ -n "${HARBOR_HOST:-}" ]]; then
      HARBOR_PORT="${HARBOR_PORT:-8080}"
    else
      log_error "external registry requires HARBOR_EXTERNAL=host:port (or HARBOR_HOST); no LAN default"
      return 1
    fi
    HARBOR_REGISTRY="${HARBOR_HOST}:${HARBOR_PORT}"
    # K8s manifests and pull secrets always use harbor.local; hosts + registries.yaml map to endpoint.
    HARBOR_IMAGE_REGISTRY="${HARBOR_ALIAS}:${HARBOR_PORT}"
    return 0
  fi

  HARBOR_MODE="in-vm"
  HARBOR_HOST="${HARBOR_HOST:-$(detect_vm_primary_ip)}"
  HARBOR_PORT="${HARBOR_PORT:-8080}"
  HARBOR_REGISTRY="${HARBOR_HOST}:${HARBOR_PORT}"
  HARBOR_IMAGE_REGISTRY="${HARBOR_ALIAS}:${HARBOR_PORT}"
}

render_template() {
  local template="$1"
  sed \
    -e "s|@HARBOR_REGISTRY@|${HARBOR_REGISTRY}|g" \
    -e "s|@HARBOR_ALIAS@|${HARBOR_ALIAS}|g" \
    -e "s|@HARBOR_PORT@|${HARBOR_PORT}|g" \
    -e "s|@HARBOR_CA_FILE@|${2:-}|g" \
    -e "s|@HARBOR_TLS_INSECURE@|${3:-}|g" \
    "${template}"
}

registry_k3s_ca_block() {
  local k3s_ca="/etc/rancher/k3s/harbor-ca.crt"
  if [[ -f "${k3s_ca}" ]]; then
    printf '      ca_file: %s' "${k3s_ca}"
  else
    printf '      insecure_skip_verify: true'
  fi
}

configure_k3s_registries() {
  local changed=0
  local ca_block tls_mode tmp
  ca_block="$(registry_k3s_ca_block)"
  if [[ "${ca_block}" == *ca_file* ]]; then
    tls_mode="ca"
  else
    tls_mode="insecure"
  fi

  if [[ ! -f "${REGISTRIES_TEMPLATE}" ]]; then
    log_error "registries template not found: ${REGISTRIES_TEMPLATE}"
    return 1
  fi

  tmp="$(mktemp)"
  render_template "${REGISTRIES_TEMPLATE}" "${ca_block}" "${tls_mode}" >"${tmp}"
  if write_if_changed "${K3S_REGISTRIES}" <"${tmp}"; then
    changed=1
  fi
  rm -f "${tmp}"

  if (( changed )) && command -v systemctl >/dev/null 2>&1 \
    && run_as_root systemctl is-active --quiet k3s 2>/dev/null; then
    log_info "restarting k3s to apply registry config..."
    run_as_root systemctl restart k3s
  fi
}

configure_podman_registries() {
  local tmp
  if [[ ! -f "${PODMAN_REGISTRIES_TEMPLATE}" ]]; then
    log_error "podman registries template not found: ${PODMAN_REGISTRIES_TEMPLATE}"
    return 1
  fi
  tmp="$(mktemp)"
  render_template "${PODMAN_REGISTRIES_TEMPLATE}" "" "" >"${tmp}"
  write_if_changed "${PODMAN_REGISTRIES}" <"${tmp}" || true
  rm -f "${tmp}"
}

write_registry_env_file() {
  run_as_root mkdir -p "$(dirname "${REGISTRY_ENV_FILE}")"
  write_if_changed "${REGISTRY_ENV_FILE}" <<EOF || true
# Generated by registry bootstrap — source before deploy-apps / sealed-secrets / CI
HARBOR_MODE=${HARBOR_MODE}
HARBOR_HOST=${HARBOR_HOST}
HARBOR_PORT=${HARBOR_PORT}
HARBOR_REGISTRY=${HARBOR_REGISTRY}
HARBOR_ALIAS=${HARBOR_ALIAS}
HARBOR_IMAGE_REGISTRY=${HARBOR_IMAGE_REGISTRY}
HARBOR_PROJECT=${HARBOR_PROJECT}
SELF_CONTAINED=${SELF_CONTAINED:-1}
HARBOR_EXTERNAL=${HARBOR_EXTERNAL:-}
EOF
}

source_registry_env() {
  if [[ -f "${REGISTRY_ENV_FILE}" ]]; then
    # shellcheck disable=SC1090
    set -a
    source "${REGISTRY_ENV_FILE}"
    set +a
    return 0
  fi
  return 1
}

harbor_auth_header() {
  printf 'Authorization: Basic %s' \
    "$(printf '%s:%s' "${HARBOR_ADMIN_USER}" "${HARBOR_ADMIN_PASSWORD}" | base64 -w0 2>/dev/null \
      || printf '%s:%s' "${HARBOR_ADMIN_USER}" "${HARBOR_ADMIN_PASSWORD}" | base64)"
}

load_harbor_admin_credentials() {
  local yml="${HARBOR_INSTALL_DIR}/harbor.yml"
  local pw

  [[ -f "${yml}" ]] || return 0
  pw="$(grep -E '^harbor_admin_password:' "${yml}" 2>/dev/null \
    | sed -E 's/^harbor_admin_password:[[:space:]]*//' || true)"
  if [[ -n "${pw}" && "${pw}" != "${HARBOR_ADMIN_PASSWORD}" ]]; then
    HARBOR_ADMIN_PASSWORD="${pw}"
    log_info "loaded Harbor admin password from ${yml}"
  fi
}

harbor_container_running() {
  local name="$1"
  command -v docker >/dev/null 2>&1 || return 1
  if docker ps --format '{{.Names}}' 2>/dev/null | grep -qx "${name}"; then
    return 0
  fi
  if declare -F run_as_root >/dev/null 2>&1; then
    run_as_root docker ps --format '{{.Names}}' 2>/dev/null | grep -qx "${name}"
    return $?
  fi
  return 1
}

load_harbor_admin_credentials_from_core() {
  local container="${HARBOR_CORE_CONTAINER:-harbor-core}"
  local pw

  harbor_container_running "${container}" || return 1
  pw="$(run_as_root docker exec "${container}" env 2>/dev/null \
    | sed -n 's/^HARBOR_ADMIN_PASSWORD=//p' | head -1 || true)"
  [[ -n "${pw}" ]] || return 1
  if [[ "${pw}" != "${HARBOR_ADMIN_PASSWORD}" ]]; then
    HARBOR_ADMIN_PASSWORD="${pw}"
    log_info "loaded Harbor admin password from ${container} env"
  fi
  return 0
}

harbor_tls_ca_file() {
  local ca="${HARBOR_CERTS_DIR:-/opt/harbor/certs}/ca.crt"
  if [[ -f "${ca}" ]]; then
    printf '%s\n' "${ca}"
    return 0
  fi
  if [[ -f "${HARBOR_CA_CERT:-}" ]]; then
    printf '%s\n' "${HARBOR_CA_CERT}"
    return 0
  fi
  return 1
}

harbor_https_api_bases() {
  printf '%s\n' \
    "https://${HARBOR_ALIAS}:443" \
    "https://${HARBOR_ALIAS}"
}

harbor_api_auth_redirects_to_https() {
  local base="${HARBOR_API_BASE:-}" code
  [[ -n "${base}" && "${base}" == http://* ]] || return 1
  code="$(curl -s -o /dev/null -w '%{http_code}' \
    "${base}/api/v2.0/users/current" 2>/dev/null || echo "000")"
  [[ "${code}" == "308" || "${code}" == "301" || "${code}" == "302" || "${code}" == "307" ]]
}

harbor_upgrade_api_base_to_https() {
  local base ca code
  harbor_tls_ca_file >/dev/null 2>&1 || return 1
  ca="$(harbor_tls_ca_file)"
  while IFS= read -r base; do
    [[ -n "${base}" ]] || continue
    if curl -fsS --cacert "${ca}" "${base}/api/v2.0/systeminfo" >/dev/null 2>&1; then
      HARBOR_API_BASE="${base}"
      return 0
    fi
  done < <(harbor_https_api_bases)
  return 1
}

harbor_admin_auth_ok() {
  local base auth code ca ca_opt=()
  auth="$(harbor_auth_header)"
  if ca="$(harbor_tls_ca_file 2>/dev/null)"; then
    ca_opt=(--cacert "${ca}")
  fi
  while IFS= read -r base; do
    [[ -n "${base}" ]] || continue
    code="$(curl -s -o /dev/null -w '%{http_code}' \
      "${ca_opt[@]}" \
      -H "${auth}" \
      "${base}/api/v2.0/users/current" 2>/dev/null || echo "000")"
    if [[ "${code}" == "200" ]]; then
      HARBOR_API_BASE="${base}"
      return 0
    fi
  done < <(
    if [[ -n "${HARBOR_API_BASE:-}" ]]; then
      printf '%s\n' "${HARBOR_API_BASE}"
    fi
    harbor_https_api_bases
    harbor_api_bases
  )
  return 1
}

harbor_api_bases() {
  if [[ "${HARBOR_MODE}" == "in-vm" ]]; then
    printf '%s\n' \
      "http://${HARBOR_REGISTRY}" \
      "http://${HARBOR_ALIAS}:${HARBOR_PORT}"
  else
    printf '%s\n' \
      "http://${HARBOR_REGISTRY}" \
      "http://${HARBOR_ALIAS}:${HARBOR_PORT}"
  fi
}

harbor_api_ready() {
  local base vm_ip hosts_ip
  vm_ip="$(detect_vm_primary_ip)"
  while IFS= read -r base; do
    [[ -n "${base}" ]] || continue
    if [[ "${HARBOR_MODE}" == "in-vm" ]]; then
      hosts_ip="$(getent ahostsv4 "${HARBOR_ALIAS}" 2>/dev/null | awk '{print $1}' | head -1 || true)"
      if [[ "${base}" == "http://${HARBOR_ALIAS}:${HARBOR_PORT}" ]] \
        && [[ -n "${hosts_ip}" && "${hosts_ip}" != "${vm_ip}" ]]; then
        continue
      fi
    fi
    if curl -fsS "${base}/api/v2.0/systeminfo" >/dev/null 2>&1; then
      HARBOR_API_BASE="${base}"
      return 0
    fi
  done < <(harbor_api_bases)
  return 1
}

resolve_harbor_api_base() {
  if harbor_api_ready; then
    sync_harbor_registry_endpoint
    if harbor_api_auth_redirects_to_https && harbor_upgrade_api_base_to_https; then
      log_info "Harbor API auth uses HTTPS (${HARBOR_API_BASE})"
    fi
    return 0
  fi
  return 1
}

sync_harbor_registry_endpoint() {
  local base="${HARBOR_API_BASE:-}"
  local host ip vm_ip

  [[ -n "${base}" ]] || return 0
  host="${base#http://}"
  host="${host%%/*}"
  if [[ "${host}" == *:* ]]; then
    host="${host%%:*}"
  fi

  if [[ "${HARBOR_MODE}" == "in-vm" ]]; then
    vm_ip="$(detect_vm_primary_ip)"
    HARBOR_HOST="${vm_ip}"
    HARBOR_REGISTRY="${HARBOR_ALIAS}:${HARBOR_PORT}"
    return 0
  fi

  if [[ "${host}" == "${HARBOR_ALIAS}" ]]; then
    ip="$(getent ahostsv4 "${HARBOR_ALIAS}" 2>/dev/null | awk '{print $1}' | head -1 || true)"
    if [[ -n "${ip}" ]] \
      && curl -fsS "http://${ip}:${HARBOR_PORT}/api/v2.0/systeminfo" >/dev/null 2>&1; then
      if [[ "${HARBOR_HOST}" != "${ip}" ]]; then
        log_info "syncing Harbor registry endpoint to reachable IP ${ip} (was ${HARBOR_HOST})"
        HARBOR_HOST="${ip}"
        HARBOR_REGISTRY="${HARBOR_HOST}:${HARBOR_PORT}"
      fi
      return 0
    fi
    if [[ "${HARBOR_REGISTRY}" != "${HARBOR_ALIAS}:${HARBOR_PORT}" ]]; then
      log_info "Harbor API reachable via ${HARBOR_ALIAS}; using alias for registry endpoint"
      HARBOR_REGISTRY="${HARBOR_ALIAS}:${HARBOR_PORT}"
    fi
    return 0
  fi

  if [[ "${host}" != "${HARBOR_HOST}" ]]; then
    log_info "syncing Harbor registry endpoint to ${host}:${HARBOR_PORT} (was ${HARBOR_HOST}:${HARBOR_PORT})"
    HARBOR_HOST="${host}"
    HARBOR_REGISTRY="${HARBOR_HOST}:${HARBOR_PORT}"
  fi
}

harbor_api_url() {
  local path="$1"
  local base="${HARBOR_API_BASE:-}"
  if [[ -z "${base}" ]] && ! resolve_harbor_api_base; then
    return 1
  fi
  printf '%s%s' "${HARBOR_API_BASE}" "${path}"
}

set_harbor_hosts_entry() {
  local ip="$1"
  local tmp

  tmp="$(mktemp)"
  if [[ -f /etc/hosts ]]; then
    grep -vE "[[:space:]]${HARBOR_ALIAS}([[:space:]]|$)" /etc/hosts >"${tmp}" || true
  fi
  printf '%s %s\n' "${ip}" "${HARBOR_ALIAS}" >>"${tmp}"
  run_as_root install -m 0644 "${tmp}" /etc/hosts
  rm -f "${tmp}"
}

ensure_harbor_hosts_entry() {
  local current_ip vm_ip

  if [[ "${HARBOR_MODE}" == "in-vm" ]]; then
    vm_ip="$(detect_vm_primary_ip)"
    HARBOR_HOST="${vm_ip}"
    HARBOR_REGISTRY="${HARBOR_HOST}:${HARBOR_PORT}"
    current_ip="$(getent ahostsv4 "${HARBOR_ALIAS}" 2>/dev/null | awk '{print $1}' | head -1 || true)"
    if [[ "${current_ip}" != "${HARBOR_HOST}" ]]; then
      if [[ -n "${current_ip}" ]]; then
        log_info "correcting /etc/hosts for in-VM Harbor: ${HARBOR_ALIAS} -> ${HARBOR_HOST} (was ${current_ip})"
      else
        log_info "adding /etc/hosts entry for in-VM Harbor: ${HARBOR_HOST} ${HARBOR_ALIAS}"
      fi
      set_harbor_hosts_entry "${HARBOR_HOST}"
    else
      log_info "unchanged: /etc/hosts entry for ${HARBOR_ALIAS} (${current_ip})"
    fi
    return 0
  fi

  current_ip="$(getent ahostsv4 "${HARBOR_ALIAS}" 2>/dev/null | awk '{print $1}' | head -1 || true)"
  if [[ -n "${current_ip}" ]]; then
    if [[ "${HARBOR_HOST}" != "${current_ip}" ]]; then
      log_info "using existing /etc/hosts mapping: ${HARBOR_ALIAS} -> ${current_ip} (detected ${HARBOR_HOST})"
      HARBOR_HOST="${current_ip}"
      HARBOR_REGISTRY="${HARBOR_HOST}:${HARBOR_PORT}"
    else
      log_info "unchanged: /etc/hosts entry for ${HARBOR_ALIAS} (${current_ip})"
    fi
    return 0
  fi

  log_info "adding /etc/hosts entry: ${HARBOR_HOST} ${HARBOR_ALIAS}"
  set_harbor_hosts_entry "${HARBOR_HOST}"
}

configure_podman_cert_dir() {
  local ca_file="$1"
  local podman_certs="/etc/containers/certs.d/${HARBOR_REGISTRY}"
  if [[ ! -f "${ca_file}" ]]; then
    return 0
  fi
  run_as_root mkdir -p "${podman_certs}"
  if [[ ! -f "${podman_certs}/ca.crt" ]] || ! cmp -s "${ca_file}" "${podman_certs}/ca.crt"; then
    run_as_root install -m 0644 "${ca_file}" "${podman_certs}/ca.crt"
    log_info "updated podman CA: ${podman_certs}/ca.crt"
  else
    log_info "unchanged: ${podman_certs}/ca.crt"
  fi
  local alias_certs="/etc/containers/certs.d/${HARBOR_ALIAS}:${HARBOR_PORT}"
  run_as_root mkdir -p "${alias_certs}"
  if [[ ! -f "${alias_certs}/ca.crt" ]] || ! cmp -s "${ca_file}" "${alias_certs}/ca.crt"; then
    run_as_root install -m 0644 "${ca_file}" "${alias_certs}/ca.crt"
    log_info "updated podman CA: ${alias_certs}/ca.crt"
  fi
}

install_system_harbor_ca() {
  local ca_file="$1"
  local system_ca="/usr/local/share/ca-certificates/harbor-ca.crt"
  local k3s_ca="/etc/rancher/k3s/harbor-ca.crt"
  local changed=0

  if [[ ! -f "${ca_file}" ]]; then
    log_warn "Harbor CA not available; using insecure registry config only"
    return 0
  fi

  if [[ ! -f "${system_ca}" ]] || ! cmp -s "${ca_file}" "${system_ca}"; then
    run_as_root install -m 0644 "${ca_file}" "${system_ca}"
    run_as_root update-ca-certificates
    log_info "updated system CA trust: ${system_ca}"
    changed=1
  else
    log_info "unchanged: ${system_ca}"
  fi

  if [[ ! -f "${k3s_ca}" ]] || ! cmp -s "${ca_file}" "${k3s_ca}"; then
    run_as_root install -m 0644 "${ca_file}" "${k3s_ca}"
    log_info "updated k3s CA: ${k3s_ca}"
    changed=1
  else
    log_info "unchanged: ${k3s_ca}"
  fi

  configure_podman_cert_dir "${ca_file}"

  if (( changed )) && command -v systemctl >/dev/null 2>&1 \
    && run_as_root systemctl is-active --quiet k3s 2>/dev/null; then
    log_info "restarting k3s to apply CA changes..."
    run_as_root systemctl restart k3s
  fi
}

fetch_harbor_ca_from_api() {
  local tmp_ca base
  tmp_ca="$(mktemp)"
  if [[ -f "${HARBOR_CA_CERT}" ]]; then
    cp "${HARBOR_CA_CERT}" "${tmp_ca}"
    echo "${tmp_ca}"
    return 0
  fi
  while IFS= read -r base; do
    [[ -n "${base}" ]] || continue
    if curl -fsSL "${base}/api/v2.0/systeminfo/getcert" -o "${tmp_ca}" 2>/dev/null \
      && [[ -s "${tmp_ca}" ]]; then
      echo "${tmp_ca}"
      return 0
    fi
  done < <(harbor_api_bases)
  rm -f "${tmp_ca}"
  return 1
}

configure_harbor_trust() {
  local tmp_ca="" ca_file=""
  if tmp_ca="$(fetch_harbor_ca_from_api)"; then
    ca_file="${tmp_ca}"
    install_system_harbor_ca "${ca_file}"
    rm -f "${tmp_ca}"
  else
    log_warn "Harbor CA not available; registry mirrors use insecure TLS skip"
  fi
  configure_k3s_registries
  configure_podman_registries
}

apply_registry_runtime_config() {
  resolve_harbor_config
  log_info "registry mode=${HARBOR_MODE} registry=${HARBOR_REGISTRY} images=${HARBOR_IMAGE_REGISTRY}"
  ensure_harbor_hosts_entry
  configure_harbor_trust
  write_registry_env_file
}
