#!/usr/bin/env bash
# Harbor / k3s / Podman registry resolution — self-contained in-VM vs legacy external.
# Source after scripts/lib/common.sh. Requires write_if_changed + run_as_root in caller
# (bootstrap-vm.sh, deploy-registry.sh) or define stubs below.

set -euo pipefail

REGISTRY_ENV_FILE="${REGISTRY_ENV_FILE:-/etc/fluxo-caixa/registry.env}"
K3S_REGISTRIES="${K3S_REGISTRIES:-/etc/rancher/k3s/registries.yaml}"
PODMAN_REGISTRIES="${PODMAN_REGISTRIES:-/etc/containers/registries.conf.d/999-harbor.conf}"
HARBOR_PROJECT="${HARBOR_PROJECT:-fluxo-caixa}"
HARBOR_ALIAS="${HARBOR_ALIAS:-harbor.local}"
HARBOR_PORT="${HARBOR_PORT:-8080}"

SCRIPT_DIR_REGISTRY="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT_REGISTRY="$(cd "${SCRIPT_DIR_REGISTRY}/../.." && pwd)"
HARBOR_CA_CERT="${HARBOR_CA_CERT:-${REPO_ROOT_REGISTRY}/deploy/certs/harbor-ca.crt}"
REGISTRIES_TEMPLATE="${REGISTRIES_TEMPLATE:-${REPO_ROOT_REGISTRY}/deploy/registry/registries.yaml.in}"
PODMAN_REGISTRIES_TEMPLATE="${PODMAN_REGISTRIES_TEMPLATE:-${REPO_ROOT_REGISTRY}/deploy/registry/podman-registries.conf.in}"

# Populated by resolve_harbor_config()
HARBOR_MODE=""
HARBOR_HOST=""
HARBOR_REGISTRY=""
HARBOR_IMAGE_REGISTRY=""

detect_vm_primary_ip() {
  local ip
  ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  echo "${ip:-127.0.0.1}"
}

parse_harbor_external() {
  local external="${1}"
  local host port
  if [[ "${external}" == *:* ]]; then
    host="${external%%:*}"
    port="${external##*:}"
  else
    host="${external}"
    port="${HARBOR_PORT}"
  fi
  HARBOR_HOST="${host}"
  HARBOR_PORT="${port}"
}

resolve_harbor_config() {
  if [[ "${SELF_CONTAINED:-1}" == "0" ]] || [[ -n "${HARBOR_EXTERNAL:-}" ]]; then
    HARBOR_MODE="external"
    if [[ -n "${HARBOR_EXTERNAL:-}" ]]; then
      parse_harbor_external "${HARBOR_EXTERNAL}"
    elif [[ -n "${HARBOR_HOST:-}" ]]; then
      HARBOR_PORT="${HARBOR_PORT:-8080}"
    else
      log_error "external registry requires HARBOR_EXTERNAL=host:port (or HARBOR_HOST); no LAN default"
      return 1
    fi
    HARBOR_REGISTRY="${HARBOR_HOST}:${HARBOR_PORT}"
    # K8s manifests and pull secrets always use harbor.local; hosts + registries.yaml map to endpoint.
    HARBOR_IMAGE_REGISTRY="${HARBOR_ALIAS}:${HARBOR_PORT}"
    return 0
  fi

  HARBOR_MODE="in-vm"
  HARBOR_HOST="${HARBOR_HOST:-$(detect_vm_primary_ip)}"
  HARBOR_PORT="${HARBOR_PORT:-8080}"
  HARBOR_REGISTRY="${HARBOR_HOST}:${HARBOR_PORT}"
  HARBOR_IMAGE_REGISTRY="${HARBOR_ALIAS}:${HARBOR_PORT}"
}

render_template() {
  local template="$1"
  sed \
    -e "s|@HARBOR_REGISTRY@|${HARBOR_REGISTRY}|g" \
    -e "s|@HARBOR_ALIAS@|${HARBOR_ALIAS}|g" \
    -e "s|@HARBOR_PORT@|${HARBOR_PORT}|g" \
    -e "s|@HARBOR_CA_FILE@|${2:-}|g" \
    -e "s|@HARBOR_TLS_INSECURE@|${3:-}|g" \
    "${template}"
}

registry_k3s_ca_block() {
  local k3s_ca="/etc/rancher/k3s/harbor-ca.crt"
  if [[ -f "${k3s_ca}" ]]; then
    printf '      ca_file: %s' "${k3s_ca}"
  else
    printf '      insecure_skip_verify: true'
  fi
}

configure_k3s_registries() {
  local changed=0
  local ca_block tls_mode tmp
  ca_block="$(registry_k3s_ca_block)"
  if [[ "${ca_block}" == *ca_file* ]]; then
    tls_mode="ca"
  else
    tls_mode="insecure"
  fi

  if [[ ! -f "${REGISTRIES_TEMPLATE}" ]]; then
    log_error "registries template not found: ${REGISTRIES_TEMPLATE}"
    return 1
  fi

  tmp="$(mktemp)"
  render_template "${REGISTRIES_TEMPLATE}" "${ca_block}" "${tls_mode}" >"${tmp}"
  if write_if_changed "${K3S_REGISTRIES}" <"${tmp}"; then
    changed=1
  fi
  rm -f "${tmp}"

  if (( changed )) && command -v systemctl >/dev/null 2>&1 \
    && run_as_root systemctl is-active --quiet k3s 2>/dev/null; then
    log_info "restarting k3s to apply registry config..."
    run_as_root systemctl restart k3s
  fi
}

configure_podman_registries() {
  local tmp
  if [[ ! -f "${PODMAN_REGISTRIES_TEMPLATE}" ]]; then
    log_error "podman registries template not found: ${PODMAN_REGISTRIES_TEMPLATE}"
    return 1
  fi
  tmp="$(mktemp)"
  render_template "${PODMAN_REGISTRIES_TEMPLATE}" "" "" >"${tmp}"
  write_if_changed "${PODMAN_REGISTRIES}" <"${tmp}" || true
  rm -f "${tmp}"
}

write_registry_env_file() {
  run_as_root mkdir -p "$(dirname "${REGISTRY_ENV_FILE}")"
  write_if_changed "${REGISTRY_ENV_FILE}" <<EOF || true
# Generated by registry bootstrap — source before deploy-apps / sealed-secrets / CI
HARBOR_MODE=${HARBOR_MODE}
HARBOR_HOST=${HARBOR_HOST}
HARBOR_PORT=${HARBOR_PORT}
HARBOR_REGISTRY=${HARBOR_REGISTRY}
HARBOR_ALIAS=${HARBOR_ALIAS}
HARBOR_IMAGE_REGISTRY=${HARBOR_IMAGE_REGISTRY}
HARBOR_PROJECT=${HARBOR_PROJECT}
SELF_CONTAINED=${SELF_CONTAINED:-1}
HARBOR_EXTERNAL=${HARBOR_EXTERNAL:-}
EOF
}

source_registry_env() {
  if [[ -f "${REGISTRY_ENV_FILE}" ]]; then
    # shellcheck disable=SC1090
    set -a
    source "${REGISTRY_ENV_FILE}"
    set +a
    return 0
  fi
  return 1
}

ensure_harbor_hosts_entry() {
  if grep -qE "[[:space:]]${HARBOR_ALIAS}([[:space:]]|$)" /etc/hosts 2>/dev/null; then
    log_info "unchanged: /etc/hosts entry for ${HARBOR_ALIAS}"
    return 0
  fi
  log_info "adding /etc/hosts entry: ${HARBOR_HOST} ${HARBOR_ALIAS}"
  printf '%s %s\n' "${HARBOR_HOST}" "${HARBOR_ALIAS}" | run_as_root tee -a /etc/hosts >/dev/null
}

configure_podman_cert_dir() {
  local ca_file="$1"
  local podman_certs="/etc/containers/certs.d/${HARBOR_REGISTRY}"
  if [[ ! -f "${ca_file}" ]]; then
    return 0
  fi
  run_as_root mkdir -p "${podman_certs}"
  if [[ ! -f "${podman_certs}/ca.crt" ]] || ! cmp -s "${ca_file}" "${podman_certs}/ca.crt"; then
    run_as_root install -m 0644 "${ca_file}" "${podman_certs}/ca.crt"
    log_info "updated podman CA: ${podman_certs}/ca.crt"
  else
    log_info "unchanged: ${podman_certs}/ca.crt"
  fi
  local alias_certs="/etc/containers/certs.d/${HARBOR_ALIAS}:${HARBOR_PORT}"
  run_as_root mkdir -p "${alias_certs}"
  if [[ ! -f "${alias_certs}/ca.crt" ]] || ! cmp -s "${ca_file}" "${alias_certs}/ca.crt"; then
    run_as_root install -m 0644 "${ca_file}" "${alias_certs}/ca.crt"
    log_info "updated podman CA: ${alias_certs}/ca.crt"
  fi
}

install_system_harbor_ca() {
  local ca_file="$1"
  local system_ca="/usr/local/share/ca-certificates/harbor-ca.crt"
  local k3s_ca="/etc/rancher/k3s/harbor-ca.crt"
  local changed=0

  if [[ ! -f "${ca_file}" ]]; then
    log_warn "Harbor CA not available; using insecure registry config only"
    return 0
  fi

  if [[ ! -f "${system_ca}" ]] || ! cmp -s "${ca_file}" "${system_ca}"; then
    run_as_root install -m 0644 "${ca_file}" "${system_ca}"
    run_as_root update-ca-certificates
    log_info "updated system CA trust: ${system_ca}"
    changed=1
  else
    log_info "unchanged: ${system_ca}"
  fi

  if [[ ! -f "${k3s_ca}" ]] || ! cmp -s "${ca_file}" "${k3s_ca}"; then
    run_as_root install -m 0644 "${ca_file}" "${k3s_ca}"
    log_info "updated k3s CA: ${k3s_ca}"
    changed=1
  else
    log_info "unchanged: ${k3s_ca}"
  fi

  configure_podman_cert_dir "${ca_file}"

  if (( changed )) && command -v systemctl >/dev/null 2>&1 \
    && run_as_root systemctl is-active --quiet k3s 2>/dev/null; then
    log_info "restarting k3s to apply CA changes..."
    run_as_root systemctl restart k3s
  fi
}

fetch_harbor_ca_from_api() {
  local tmp_ca
  tmp_ca="$(mktemp)"
  if [[ -f "${HARBOR_CA_CERT}" ]]; then
    cp "${HARBOR_CA_CERT}" "${tmp_ca}"
    echo "${tmp_ca}"
    return 0
  fi
  if curl -fsSL "http://${HARBOR_REGISTRY}/api/v2.0/systeminfo/getcert" -o "${tmp_ca}" 2>/dev/null \
    && [[ -s "${tmp_ca}" ]]; then
    echo "${tmp_ca}"
    return 0
  fi
  rm -f "${tmp_ca}"
  return 1
}

configure_harbor_trust() {
  local tmp_ca="" ca_file=""
  if tmp_ca="$(fetch_harbor_ca_from_api)"; then
    ca_file="${tmp_ca}"
    install_system_harbor_ca "${ca_file}"
    rm -f "${tmp_ca}"
  else
    log_warn "Harbor CA not available; registry mirrors use insecure TLS skip"
  fi
  configure_k3s_registries
  configure_podman_registries
}

apply_registry_runtime_config() {
  resolve_harbor_config
  log_info "registry mode=${HARBOR_MODE} registry=${HARBOR_REGISTRY} images=${HARBOR_IMAGE_REGISTRY}"
  ensure_harbor_hosts_entry
  configure_harbor_trust
  write_registry_env_file
}
