apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-lancamentos
spec:
  template:
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-lancamentos-outbox-worker
spec:
  template:
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate-lancamentos
spec:
  template:
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-consolidado
spec:
  template:
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate-consolidado
spec:
  template:
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
