apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: security

configMapGenerator:
  - name: ory-bootstrap
    files:
      - bootstrap.sh=../../platform/ory/bootstrap.sh
    options:
      disableNameSuffixHash: true

resources:
  - token-hook.yaml
  - bootstrap-job.yaml
