apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: security

configMapGenerator:
  - name: authentik-bootstrap
    files:
      - bootstrap.sh=../../platform/authentik/bootstrap.sh
    options:
      disableNameSuffixHash: true

resources:
  - bootstrap-job.yaml
