apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fluxo-caixa

resources:
  - ../../base
  - sealed

patches:
  - path: patches/replicas.yaml
  - path: patches/lancamentos-environment.yaml
  - path: patches/consolidado-environment.yaml
  - path: patches/consulta-environment.yaml

commonLabels:
  environment: dev
